@startuml

!theme crt-green

!include ParserStates-simple.puml

ChartWithPoints --> PointClusterImage : GenerateClusterImage

ChartOrigin --> ChartDimensions : FindDimensions

state chartLayout <<join>>
ChartDimensions --> chartLayout
YAxis --> chartLayout
chartLayout --> ChartLayout
ChartLayout --> ChartLayoutImage : GenerateLayoutImage

state chartImage <<join>>
ChartLayoutImage --> chartImage
LineOverlayChart --> chartImage
chartImage --> AllDebugImages
AllDebugImages --> CombinedDebugImage : GenerateCombinedDebugImage

MergedChart --> LineOverlayChart : GenerateLineOverlay

@enduml
