name: Release
on:
  push:
    paths-ignore:
      - 'FiveNightsAtTorstens/**'
  workflow_dispatch:

jobs:
  build:
    name: Create release build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore -r win-x64
      - name: Build
        run: |
          cd chart2csvConsole
          dotnet build -c Release -r win-x64 --no-restore
      - name: Publish
        run: |
          cd chart2csvConsole
          dotnet publish -c Release -r win-x64
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: chart2csvConsole
          path: chart2csvConsole/bin/Release/net6.0/win-x64/publish/chart2csvConsole.exe
